version: 2
jobs:
  build:
    working_directory: ~/.dotfiles
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "misc/Brewfile" }}
      - run:
          name: "Install apt dependencies"
          command: apt-get update && apt-get install -y build-essential python python-pip libxml-parser-perl curl ruby
      - run:
          name: "Install Homebrew"
          command: yes '' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" || echo "Homebrew was already installed"
      - run:
          name: "Install fish"
          command: PATH="$HOME/.linuxbrew/bin:$PATH" brew install fish
      - run:
          name: "Run linux bootstrap script"
          command: script/bootstrap_linux
      - run:
          name: "Remove bin folder (FIXME)"
          command: "rm -rf $HOME/bin"
      - run:
          name: "Run bootstrap script"
          command: echo -ne "test@example.com\nJustus Perlwitz\n" | env PATH="$HOME/.linuxbrew/bin:$PATH" script/bootstrap
      - save_cache:
          key: cache-{{ checksum "misc/Brewfile" }}
          paths:
            - ~/.linuxbrew
